// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOiWBI9QsMfjPSo25mAXhphZUxBcdv9I',
    appId: '1:738630038032:web:070f9b26a0c7b687e25095',
    messagingSenderId: '738630038032',
    projectId: 'fridgering',
    authDomain: 'fridgering.firebaseapp.com',
    storageBucket: 'fridgering.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPavZIDQFxOe54zWgU2_Kc7BVrn2RGpr0',
    appId: '1:738630038032:android:e58f05420aa9af4ce25095',
    messagingSenderId: '738630038032',
    projectId: 'fridgering',
    storageBucket: 'fridgering.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1OoA0jmEETL-gWWfwMDBpC3fYDBUyVY',
    appId: '1:738630038032:ios:4fae3ed39dcdcd94e25095',
    messagingSenderId: '738630038032',
    projectId: 'fridgering',
    storageBucket: 'fridgering.appspot.com',
    iosClientId: '738630038032-s822n34lj0cf3g2r0acud39c3837kvn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridgering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd1OoA0jmEETL-gWWfwMDBpC3fYDBUyVY',
    appId: '1:738630038032:ios:2ee33bce6bff91b0e25095',
    messagingSenderId: '738630038032',
    projectId: 'fridgering',
    storageBucket: 'fridgering.appspot.com',
    iosClientId: '738630038032-nhkmomr6ujudmjdqdjqn8egkikt00jfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridgering.RunnerTests',
  );
}
